const { PresolicitudAnexoDTO } = require('./presolicitud-anexo.dto');
const { PeticionScoreDTO } = require('./peticion-score.dto');

class PreSolicitudDTO {
    cve_presolicitud;
    primer_nombre;
    segundo_nombre;
    apellido_paterno;
    apellido_materno;
    genero;
    curp;
    rfc;
    correo_electronico;
    telefono_celular;
    estado_nacimiento;
    fecha_nacimiento;
    calle;
    no_exterior;
    no_interior;
    cruzamientos;
    codigo_postal;
    estado;
    municipio;
    ciudad;
    tipo_asentamiento;
    asentamiento;
    fg_termino_condiciones;
    fg_autorizacion;
    codigo_sms;
    cve_vendedor;
    score_circulo;
    score_tipo;
    estatus_circulo;
    caja;
    cve_sucursal;
    fecha_alta;
    id_red_social;
    usuario_red_social;
    cve_categoria;
    cve_marca;
    cve_producto;
    material;
    precio_equipo;
    iva_equipo;
    precio_equipo_iva;
    enganche_minimo;
    enganche_real;
    plazo_semanal;
    pago_semanal;
    pago_semanal_capital;
    pago_semanal_interes;
    total_financiado;
    perfil_riesgo;
    celular_perfil;
    prestamo_perfil;
    motocicleta_perfil;
    estatus;
    fg_modifico_curp;
    fg_modifico_rfc;
    score;
    fg_valida_ine;
    plataforma;
    plataforma_id;
    estado_plataforma;
    fg_financiamiento_mixto;
    id_tipo_financiamiento;
    centroSap;
    score_final;
    celular_aprobado;
    prestamo_aprobado;
    motocicleta_aprobada;
    cve_presolicitud_originacion;
    fg_garantia_extendida;
    fg_membresia;
    revalidacion;
    score_telcel;
    limite_credito;
    linea_credito;
    monto_linea_credito;
    perfil_fraude;
    saldo_linea_de_credito;
    saldo_vencido_linea_de_credito;
    anexo_presolicitud;
    detalle_carrito;
    fg_evaluado_limite_credito;
    fg_white_list;
    no_creditos_activos;
    no_creditos_permitidos;
    latitud_domicilio;
    longitud_domicilio;
    fg_busqueda;
    nb_cliente;
    fg_fallo_api_telcel;
    fg_multifinanciamiento_sucursal;
    fg_multifinanciamiento_perfil;
    excedente_multifinanciamiento;
    cantidad_multifinanciamiento;
    estrategia_white_list;
    id_cupon_white_list;
    tipoActivo;
    cve_solicitud;
    originacion;
    razon_rechazo;
    razon_rechazo_detalle;
    fg_datos_actualizados;

    constructor(preapplication = {}) {
        this.cve_presolicitud = preapplication.cve_presolicitud || "";
        this.primer_nombre = preapplication.primer_nombre || "";
        this.segundo_nombre = preapplication.segundo_nombre || "";
        this.apellido_paterno = preapplication.apellido_paterno || "" ;
        this.apellido_materno = preapplication.apellido_materno || "" ;
        this.genero = preapplication.genero || "";
        this.curp = preapplication.curp || "" ;
        this.rfc = preapplication.rfc || "";
        this.correo_electronico = preapplication.correo_electronico || "" ;
        this.telefono_celular = preapplication.telefono_celular || "" ;
        this.estado_nacimiento = preapplication.estado_nacimiento || "" ;
        this.fecha_nacimiento = preapplication.fecha_nacimiento || "01/01/1900 00:00:00";
        this.calle = preapplication.calle || "" ;
        this.no_exterior = preapplication.no_exterior || "" ;
        this.no_interior = preapplication.no_interior || "" ;
        this.cruzamientos = preapplication.cruzamientos || "" ;
        this.codigo_postal = preapplication.codigo_postal || "" ;
        this.estado = preapplication.estado || "" ;
        this.municipio = preapplication.municipio || "" ;
        this.ciudad = preapplication.ciudad || "" ;
        this.tipo_asentamiento = preapplication.tipo_asentamiento || "" ;
        this.asentamiento = preapplication.asentamiento || "" ;
        this.fg_termino_condiciones = preapplication.fg_termino_condiciones || 0;
        this.fg_autorizacion = preapplication.fg_autorizacion || 0;
        this.codigo_sms = preapplication.codigo_sms ||  "" ;
        this.cve_vendedor = preapplication.cve_vendedor || "" ;
        this.score_circulo = preapplication.score_circulo || 0;
        this.score_tipo = preapplication.score_tipo || "";
        this.estatus_circulo = preapplication.estatus_circulo || 0;
        this.caja = preapplication.caja || "" ;
        this.cve_sucursal = preapplication.cve_sucursal || "" ;
        this.id_red_social = preapplication.id_red_social || 0;
        this.usuario_red_social = preapplication.usuario_red_social || "" ;
        this.fecha_alta = preapplication.fecha_alta || "01/01/1900 00:00:00";
        this.cve_categoria = preapplication.cve_categoria || "" ;
        this.cve_marca = preapplication.cve_marca || "" ;
        this.cve_producto = preapplication.cve_producto || "" ;
        this.material = preapplication.material || "" ;
        this.precio_equipo = preapplication.precio_equipo || 0;
        this.iva_equipo = preapplication.iva_equipo || 0;
        this.precio_equipo_iva = preapplication.precio_equipo_iva || 0;
        this.enganche_minimo = preapplication.enganche_minimo || 0;
        this.enganche_real = preapplication.enganche_real || 0;
        this.enganche_real = preapplication.enganche_real || 0;
        this.plazo_semanal = preapplication.plazo_semanal || 0;
        this.pago_semanal = preapplication.pago_semanal || 0;
        this.pago_semanal_capital = preapplication.pago_semanal_capital || 0;
        this.pago_semanal_interes = preapplication.pago_semanal_interes || 0;
        this.total_financiado = preapplication.total_financiado || 0;
        this.perfil_riesgo = preapplication.perfil_riesgo || "";
        this.estatus = preapplication.estatus || 0;
        this.fg_modifico_curp = preapplication.fg_modifico_curp || 0;
        this.fg_modifico_rfc = preapplication.fg_modifico_rfc || 0;
        this.score = preapplication.score || new PeticionScoreDTO();
        this.fg_valida_ine = preapplication.fg_valida_ine || 0;
        this.plataforma = preapplication.plataforma || "";
        this.plataforma_id = preapplication.plataforma_id   || "";
        this.estado_plataforma = preapplication.estado_plataforma || "";
        this.fg_financiamiento_mixto = preapplication.fg_financiamiento_mixto ||  0;
        this.id_tipo_financiamiento = preapplication.id_tipo_financiamiento || 0;
        this.centroSap = preapplication.centroSap || "";
        this.score_final = preapplication.score_final || 0;
        this.celular_aprobado = preapplication.celular_aprobado || 0;
        this.prestamo_aprobado = preapplication.prestamo_aprobado || 0;
        this.cve_presolicitud_originacion = preapplication.cve_presolicitud_originacion || "";
        this.fg_garantia_extendida = preapplication.fg_garantia_extendida || 0;
        this.fg_membresia = preapplication.fg_membresia || 0;
        this.revalidacion = preapplication.revalidacion || "";
        this.celular_perfil = preapplication.celular_perfil || "";
        this.prestamo_perfil = preapplication.prestamo_perfil || "";
        this.score_telcel = preapplication.score_telcel || 0;
        this.anexo_presolicitud = preapplication.anexo_presolicitud || new PresolicitudAnexoDTO();
        this.perfil_fraude = preapplication.perfil_fraude || "";
        this.limite_credito = preapplication.limite_credito || 0;
        this.linea_credito = preapplication.linea_credito || 0;
        this.detalle_carrito = preapplication.detalle_carrito || []
        this.saldo_linea_de_credito = preapplication.saldo_linea_de_credito || 0;
        this.saldo_vencido_linea_de_credito = preapplication.saldo_vencido_linea_de_credito || 0;
        this.motocicleta_aprobada = preapplication.motocicleta_aprobada || 0;
        this.motocicleta_perfil = preapplication.motocicleta_perfil || "";
        this.monto_linea_credito = preapplication.monto_linea_credito ||  0;
        this.fg_evaluado_limite_credito = preapplication.fg_evaluado_limite_credito || 0;
        this.fg_white_list = preapplication.fg_white_list || 0;
        this.no_creditos_activos = preapplication.no_creditos_activos || 0;
        this.no_creditos_permitidos = preapplication.no_creditos_permitidos || 0;
        this.fg_busqueda = preapplication.fg_busqueda || 0;
        this.nb_cliente = preapplication.nb_cliente || "";
        this.fg_fallo_api_telcel = preapplication.fg_fallo_api_telcel || 0;
        this.fg_multifinanciamiento_perfil = preapplication.fg_multifinanciamiento_perfil || 0;
        this.fg_multifinanciamiento_sucursal = preapplication.fg_multifinanciamiento_sucursal || 0;
        this.excedente_multifinanciamiento = preapplication.excedente_multifinanciamiento || 0;
        this.cantidad_multifinanciamiento = preapplication.cantidad_multifinanciamiento || 1;
        this.estrategia_white_list = preapplication.estrategia_white_list || "";
        this.id_cupon_white_list = preapplication.id_cupon_white_list || 0;
        this.tipoActivo = preapplication.tipoActivo || "";
        this.cve_solicitud = preapplication.cve_solicitud || "";
        this.originacion = preapplication.originacion ||  0;
        this.razon_rechazo = preapplication.razon_rechazo || "";
        this.razon_rechazo_detalle = preapplication.razon_rechazo_detalle || "";
        this.fg_datos_actualizados = preapplication.fg_datos_actualizados || 0;
        this.latitud_domicilio = preapplication.latitud_domicilio || 0;
        this.longitud_domicilio = preapplication.longitud_domicilio || 0;
    }
}

module.exports = { PreSolicitudDTO };