class SolicitudDTO {
    cve_Solicitud;
    clave_Solicitud;
    cve_Contrato;
    id_Cliente;
    cve_Cliente;
    nombre;
    cve_Producto;
    material;
    tipo_Producto;
    cve_marca;
    marca_Producto;
    modelo_Producto;
    cve_Serie;
    precio_civa;
    enganche;
    plazo;
    pago_semanal;
    total_financiado;
    saldo_vencido;
    saldo_restante;
    fecha_solicitud;
    estatus;
    cantidad_pago_pendiente;
    folio_registro_intranet;
    folio_registro_intranet_largo;
    referencia;
    sku;
    Sc_Cve_Sucursal;
    fg_existe;
    cve_vendedor;
    cj_cve_caja;
    imei_capturado;
    cve_forma_pago;
    Sc_Prefijo_General;
    folio_recibo;
    cve_presolicitud;
    centroSap;
    id_tipo_financiamiento;
    cve_presolucitud_base;

    constructor(sl = {}) {
        this.cve_Solicitud = sl.cve_Solicitud || 0;
        this.clave_Solicitud = sl.clave_Solicitud || "";
        this.cve_Contrato = sl.cve_Contrato || "";
        this.id_Cliente = sl.id_Cliente || 0;
        this.cve_Cliente = sl.cve_Cliente || "";
        this.nombre = sl.nombre || "";
        this.cve_Producto = sl.cve_Producto || "";
        this.material = sl.material || "";
        this.tipo_Producto = sl.tipo_Producto || "";
        this.cve_marca = sl.cve_marca || "";
        this.marca_Producto = sl.marca_Producto || "";
        this.modelo_Producto = sl.modelo_Producto || "";
        this.cve_Serie = sl.cve_Serie || "";
        this.precio_civa = sl.precio_civa || 0;
        this.enganche = sl.enganche || 0;
        this.plazo = sl.plazo || 0;
        this.pago_semanal = sl.pago_semanal || 0;
        this.total_financiado = sl.total_financiado || 0;
        this.saldo_vencido = sl.saldo_vencido || 0;
        this.saldo_restante = sl.saldo_restante || 0;
        this.fecha_solicitud = sl.fecha_solicitud || "01/01/1900 00:00:00";
        this.estatus = sl.estatus || "";
        this.Sc_Cve_Sucursal = sl.Sc_Cve_Sucursal || "";
        this.fg_existe = sl.fg_existe || 0;
        this.cve_vendedor = sl.cve_vendedor || "";
        this.cj_cve_caja = sl.cj_cve_caja || "";
        this.imei_capturado = sl.imei_capturado || "";
        this.cve_forma_pago = sl.cve_forma_pago || "";
        this.Sc_Prefijo_General = sl.Sc_Prefijo || "";
        this.folio_recibo = sl.folio_recibo || "";
        this.cantidad_pago_pendiente = sl.cantidad_pago_pendiente || 0;
        this.folio_registro_intranet = sl.folio_registro_intranet || "";
        this.folio_registro_intranet_largo = sl.folio_registro_intranet_largo || "";
        this.referencia = sl.referencia || "";
        this.sku = sl.sku || "";
        this.cve_presolicitud = sl.cve_presolicitud || "";
        this.centroSap = sl.centroSap || "";
        this.id_tipo_financiamiento = sl.id_tipo_financiamiento || 0;
        this.cve_presolucitud_base = sl.cve_presolucitud_base || "";
    }
}

module.exports = {SolicitudDTO};