class SolicitudPvDTO {
    cve_solicitud;
    cve_presolicitud;
    cve_contrato;
    cve_cliente;
    nombre_completo;
    cve_producto;
    material;
    tipo_producto;
    cve_marca;
    marca_producto;
    modelo_producto;
    cve_serie;
    precio_civa;
    total_financiado_interes;
    total_financiado;
    enganche;
    plazo;
    pago_semanal;
    cantidad_pago_pendiente;
    saldo_vencido;
    saldo_restante;
    folio_registro_intranet;
    folio_registro_intranet_largo;
    estatus;
    fecha_solicitud;
    nombre;
    correo_electronico;
    sc_cve_sucursal;
    fg_accion;
    fg_valida_ine;
    id_tipo_financiamiento;
    descripcion_marca_dispersion;
    descripcion_producto;
    descripcion_dispersion;
    referencia_cliente_dispersion;
    fg_recompra;
    fg_garantia_extendida;
    enganche_garantia_extendida;
    cve_producto_garantia_extendida;
    descripcion_garantia_extendida;
    fg_membresia;
    enganche_membresia;
    cve_producto_membresia;
    descripcion_membresia;
    fg_cliente_interno;
    id_cupon_white_list;

    constructor(solicitud = {}) {
        this.cve_solicitud = solicitud.cve_solicitud || "";
        this.cve_presolicitud = solicitud.cve_presolicitud || "";
        this.cve_contrato = solicitud.cve_contrato || "";
        this.cve_cliente = solicitud.cve_cliente || "";
        this.nombre_completo = solicitud.nombre_completo || "";
        this.cve_producto = solicitud.cve_producto || "";
        this.material = solicitud.material || "";
        this.tipo_producto = solicitud.tipo_producto || "";
        this.cve_marca = solicitud.cve_marca || "";
        this.marca_producto = solicitud.marca_producto || "";
        this.modelo_producto = solicitud.modelo_producto || "";
        this.cve_serie = solicitud.cve_serie || "";
        this.precio_civa = solicitud.precio_civa || 0;
        this.total_financiado_interes = solicitud.total_financiado_interes || 0;
        this.total_financiado = solicitud.total_financiado || 0;
        this.enganche = solicitud.enganche || 0;
        this.plazo = solicitud.plazo || 0;
        this.pago_semanal = solicitud.pago_semnal || 0;
        this.cantidad_pago_pendiente = solicitud.cantidad_pago_pendiente || 0;
        this.saldo_vencido = solicitud.saldo_vencido || 0;
        this.saldo_restante = solicitud.saldo_restante || 0;
        this.folio_registro_intranet = solicitud.folio_registro_intranet || "";
        this.folio_registro_intranet_largo = solicitud.folio_registro_intranet_largo || "";
        this.estatus = solicitud.estatus || "";
        this.fecha_solicitud = solicitud.fecha_solicitud || '01/01/1900 00:00:00';
        this.nombre = solicitud.nombre || "";
        this.correo_electronico = solicitud.correo_electronico || "";
        this.sc_cve_sucursal = solicitud.sc_cve_sucursal || "";
        this.fg_accion = solicitud.fg_accion || -1;
        this.fg_valida_ine = solicitud.fg_valida_ine || 0;
        this.id_tipo_financiamiento = solicitud.id_tipo_financiamiento || 0;
        this.descripcion_dispersion = solicitud.descripcion_dispersion || "";
        this.descripcion_marca_dispersion = solicitud.descripcion_dispersion || "";
        this.descripcion_producto = solicitud.descripcion_producto || "";
        this.referencia_cliente_dispersion = solicitud.referencia_cliente_dispersion || "";
        this.fg_recompra = solicitud.fg_recompra || 0;
        this.fg_garantia_extendida = solicitud.fg_garantia_extendida || 0;
        this.enganche_garantia_extendida = solicitud.enganche_garantia_extendida || 0;
        this.cve_producto_garantia_extendida = solicitud.cve_producto_garantia_extendida || "";
        this.descripcion_garantia_extendida = solicitud.descripcion_garantia_extendida || "";
        this.fg_membresia = solicitud.fg_membresia || 0;
        this.enganche_membresia = solicitud.enganche_membresia || 0;
        this.cve_producto_membresia = solicitud.cve_producto_membresia || "";
        this.descripcion_membresia = solicitud.descripcion_membresia || "";
        this.fg_cliente_interno = solicitud.fg_cliente_interno || 0;
        this.id_cupon_white_list = solicitud.id_cupon_white_list || 0;
    }
}

module.exports = { SolicitudPvDTO };